<root>
  <LegionUse>True</LegionUse>
  <LegionIndex>0</LegionIndex>
  <LegionSize>1</LegionSize>
  <CivilianUse>True</CivilianUse>
  <CivilianIndex>0</CivilianIndex>
  <CivilianSize>1</CivilianSize>
  <RaceUse>True</RaceUse>
  <RaceIndex>10</RaceIndex>
  <RaceSize>1</RaceSize>
  <TagUse> </TagUse>
  <TagIndex> </TagIndex>
  <TagSize> </TagSize>
  <StatUse>True</StatUse>
  <StatIndex>0</StatIndex>
  <StatSize>1</StatSize>
  <AllCard>1</AllCard>
</root>