<root>
  <LegionUse>True</LegionUse>
  <LegionIndex>0</LegionIndex>
  <LegionSize>3</LegionSize>
  <CivilianUse>True/True</CivilianUse>
  <CivilianIndex>0/3</CivilianIndex>
  <CivilianSize>1/2</CivilianSize>
  <RaceUse>True</RaceUse>
  <RaceIndex>0</RaceIndex>
  <RaceSize>3</RaceSize>
  <TagUse> </TagUse>
  <TagIndex> </TagIndex>
  <TagSize> </TagSize>
  <StatUse>True/True/True</StatUse>
  <StatIndex>0/2/3</StatIndex>
  <StatSize>3/1/1</StatSize>
  <AllCard>3</AllCard>
</root>