<root>
  <LegionUse> </LegionUse>
  <LegionIndex> </LegionIndex>
  <LegionSize> </LegionSize>
  <CivilianUse> </CivilianUse>
  <CivilianIndex> </CivilianIndex>
  <CivilianSize> </CivilianSize>
  <RaceUse> </RaceUse>
  <RaceIndex> </RaceIndex>
  <RaceSize> </RaceSize>
  <TagUse> </TagUse>
  <TagIndex> </TagIndex>
  <TagSize> </TagSize>
  <StatUse> </StatUse>
  <StatIndex> </StatIndex>
  <StatSize> </StatSize>
  <AllCard>0</AllCard>
</root>