<root>
  <LegionUse>True</LegionUse>
  <LegionIndex>0</LegionIndex>
  <LegionSize>4</LegionSize>
  <CivilianUse>True</CivilianUse>
  <CivilianIndex>0</CivilianIndex>
  <CivilianSize>4</CivilianSize>
  <RaceUse>True</RaceUse>
  <RaceIndex>0</RaceIndex>
  <RaceSize>4</RaceSize>
  <TagUse> </TagUse>
  <TagIndex> </TagIndex>
  <TagSize> </TagSize>
  <StatUse>True/True/True</StatUse>
  <StatIndex>0/1/2</StatIndex>
  <StatSize>4/0/1</StatSize>
  <AllCard>4</AllCard>
</root>